services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      # env file read.
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    container_name: dotnet_api
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    depends_on:
      - postgres
    restart: unless-stopped

  ui:
    container_name: react_ui
    build:
      context: ./ui
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL_COMPOSE}
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
